name: tutorial
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.6
  - scikit-learn=0.19.1
  - pip:
    - mlflow>=1.0
    - azure-core==1.5.0
    - azure-storage-blob==12.3.1
    - python-dotenv==0.13.0
    - dvc==0.94.0