script: train.py

# cluster to run training on
target: train-dev

# framework to use for training
framework: Python

# nodes to use for training
nodeCount: 1

environment:
  name: data_gen_environment
  python:
    userManagedDependencies: false
    interpreterPath: python
    condaDependenciesFile: environment.yml