name: build

on:
  issue_comment:
    types: [created]
    
jobs:
  build:
    if: startsWith(github.event.comment.body, '/build')
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - name: TR
        run: |
          COMMAND=echo '${{github.event.comment.body}}' | sed "s|/build||g"
          echo $COMMAND
