name: build

on:
  issue_comment:
    types: [created]
    
jobs:
  build:
    if: startsWith(github.event.comment.body, '/build')
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - name: TR
        run: |
          GITHUB_REF=$(echo ${{github.event.comment.body}} | sed -e "s#/build##g")
          echo "new GITHUB_REF is $GITHUB_REF"
          echo $COMMAND
