name: build

on:
  issue_comment:
    types: [created]
    
jobs:
  build:
    if: startsWith(github.event.comment.body, '/build')
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - name: Normalise command
        run: |
          COMMAND=${{github.event.comment.body#"/build"}}
          echo $COMMAND
      
