name: build

on:
  issue_comment:
    types: [created]
    
jobs:
  build:
    if: startsWith(github.event.comment.body, '/build')
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - name: print comment
        run: echo "${{github.event.comment.body}}"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
