name: build

on:
  issue_comment:
    types: [created]
    
jobs:
  build:
    if: startsWith(github.event.comment.body, '/build')
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - name: Normalise command
        run: |
          COMMENT="${{github.event.comment.body}}"
          COMMAND=${COMMENT#"/build"}
          echo $COMMAND
      
