name: build

on:
  issue_comment:
    types: [created]
    
jobs:
  build:
    if: startsWith(github.event.comment.body, '/register experiment_name')
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - name: Extract params
        id: extract
        run: |
          EXPERIMENT_NAME=$(echo "${{github.event.comment.body}}" | awk -F' ' '{print $2}' | awk -F'[=]' '{print $2}')
          RUN_ID=$(echo "${{github.event.comment.body}}" | awk -F' ' '{print $3}' | awk -F'[=]' '{print $2}')
          echo "::set-env name=EXPERIMENT_NAME::$EXPERIMENT_NAME"
          
      - name: print params
        run: |
          echo "$EXPERIMENT_NAME"
