# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:
    branches:
      - without-dvc
      - playground
      - mlflow-databricks

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    # Checkout repository
    - name: Check out repository
      id: checkout_repo
      uses: actions/checkout@v2
    
    # Setup python
    - name: Setup Python
      id: python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'

    # Setup conda
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false

    # Install MLFlow
    - name: Install MLFlow
      id: mlflow
      run: |
        pip install mlflow
    
    # Train model
    - name: Train model
      id: train_run
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        MLFLOW_TRACKING_URI: databricks
        MLFLOW_EXPRIMENT_NAME: ${{ secrets.MLFLOW_EXPRIMENT_NAME }}
        AZURE_STORAGE_CONTAINER_NAME: ${{secrets.AZURE_STORAGE_CONTAINER_NAME}}
        AZURE_STORAGE_CONNECTION_STRING: "${{secrets.AZURE_STORAGE_CONNECTION_STRING}}"
      run: |
        make train

    # Evaluate trained model
    - name: Evaluate model
      env: 
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        MLFLOW_TRACKING_URI: databricks
        MLFLOW_EXPRIMENT_NAME: ${{ secrets.MLFLOW_EXPRIMENT_NAME }}
        MLFLOW_TRAIN_RUN_ID: ${{ steps.train_run.outputs.run_id }}
      run:
        make evaluate

    # Register trained model
    - name: Register model
      env: 
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        MLFLOW_TRACKING_URI: databricks
        MLFLOW_EXPRIMENT_NAME: ${{ secrets.MLFLOW_EXPRIMENT_NAME }}
        MLFLOW_TRAIN_RUN_ID: ${{ steps.train_run.outputs.run_id }}
        MLFLOW_MODEL_NAME: TemplateModel
      run: |
        make register-model

    # Deploy trained model
    - name: Deploy model
      env:
        AZURE_ML_SERVICE_PRINCIPAL_ID: ${{ secrets.AZURE_ML_SERVICE_PRINCIPAL_ID }}
        AZURE_ML_SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.AZURE_ML_SERVICE_PRINCIPAL_PASSWORD }}
        AZURE_ML_TENANT_ID: ${{ secrets.AZURE_ML_TENANT_ID }}
        AZURE_ML_WORKSPACE_NAME: ${{ secrets.AZURE_ML_WORKSPACE_NAME }}
        AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
        AZURE_ML_SUBSCRIPTION_ID: ${{ secrets.AZURE_ML_SUBSCRIPTION_ID }}
        MLFLOW_TRACKING_URI: databricks
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        MLFLOW_EXPRIMENT_NAME: ${{ secrets.MLFLOW_EXPRIMENT_NAME }}
        MLFLOW_TRAIN_RUN_ID: ${{ steps.train_run.outputs.run_id }}
        MLFLOW_MODEL_NAME: TemplateModel
      run: |
        make deploy-model
