# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - playground

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    # Checkout repository
    - name: Check out repository
      id: checkout_repo
      uses: actions/checkout@v2
    
    # Setup python
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'

    # Install MLFlow
    - name: Install MLFlow
      run: |
        pip install mlflow
    
    # Train model on docker container
    - name: Train model
      run: |
        mlflow run .
