# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ playground ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Build with Ant
      working-directory: /home/runner/work/AccurECG_New/AccurECG_New/AccurKardia
      run: wget -P /home/runner/work/AccurECG_New/AccurECG_New/AccurKardia/WebContent/WEB-INF/lib/ https://webapp-dependency-jars.s3.amazonaws.com/aws-java-sdk-bundle-1.11.569.jar && ant -noinput -buildfile build.xml
    
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Beanstalk Deploy for app
      uses: einaregilsson/beanstalk-deploy@v9
      with:
        aws_access_key: ${{secrets.AWS_ACCESS_KEY}}
        aws_secret_key: ${{secrets.AWS_SECRET_KEY}}
        application_name: accurkardia-webapp-dev
        environment_name: accurkardia-webapp-dev
        region: us-east-1
        version_label: "ak-webapp-${{ steps.vars.outputs.sha_short }}"
        deployment_package: /home/runner/work/AccurECG_New/AccurECG_New/AccurKardia/dist/AccurKardia.war
        use_existing_version_if_available: true

    - name: Deployed!
      run: echo App deployed to ELB