# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:
    branches:
      - without-dvc
      - playground

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    # Checkout repository
    - name: Check out repository
      id: checkout_repo
      uses: actions/checkout@v2
    
    # Setup python
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'

    # Setup conda
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false

    # Install MLFlow
    - name: Install MLFlow
      run: |
        pip install mlflow
    
    # Train model
    - name: Train model
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        MLFLOW_TRACKING_URI: databricks
        MLFLOW_EXPRIMENT_NAME: ${{ secrets.MLFLOW_EXPRIMENT_NAME }}
      run: |
        make train

    # Evaluate trained model
    - name: Evaluate model
      env: 
        MLFLOW_TRAIN_RUN_ID: ${MLFLOW_RUN_ID}
    - run: echo ${MLFLOW_RUN_ID}
    - run: echo ${MLFLOW_TRAIN_RUN_ID}
